name: Variants in California
on:
  schedule:
    - cron: '50 */12 * * *'  
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: run
        name: Run
        uses: ./.github/actions/scrape
        with:
          module: variant-toplines-ca
